arts_by_bela/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('profile/', include('profiles.urls')),
    path('commission/', include('commissions.urls')),
    path('payment/', include('payments.urls')),
    path('showcase/', include('showcase.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='home')
]

profiles/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.profile, name='profile')
]

profiles/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


class UserProfile(models.Model):
    """
    A user profile model for maintaining user info
    """
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    first_name = models.CharField(
        max_length=30, null=False, blank=True)
    last_name = models.CharField(
        max_length=30, null=False, blank=True)

    def __str__(self):
        return self.user.username


@receiver(post_save, sender=User)
def create_or_update_user_profile(sender, instance, created, **kwargs):
    """
    Create or update the user profile
    """
    if created:
        UserProfile.objects.create(user=instance)
    # Existing users: just save the profile
    instance.userprofile.save()

profiles/forms.py
from django import forms
from .models import UserProfile


class UserProfileForm(forms.ModelForm):
    """
    UserProfile Model Form to select and format desired fields for
    profile template
    """
    class Meta:
        model = UserProfile
        exclude = ('user',)

    def __init__(self, *args, **kwargs):
        """
        Add placeholders and classes, remove auto-generated
        labels and set autofocus on first field
        """
        super().__init__(*args, **kwargs)

        for field in self.fields:
            self.fields[field].widget.attrs['class'] = ('validate')
            self.fields[field].label = False

profiles/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.db.models import Q
from .models import UserProfile
from .forms import UserProfileForm
from commissions.models import Commission


@login_required
def profile(request):
    """ A view to return the profile page """

    profile = get_object_or_404(UserProfile, user=request.user)
    if request.method == 'POST':
        form = UserProfileForm(request.POST, instance=profile)
        if form.is_valid():
            form.save()
            messages.success(request, 'Profile updated successfully')
        else:
            messages.error(request,
                           ('Update failed. Please ensure '
                            'the form is valid.'))
    else:
        form = UserProfileForm(instance=profile)

    if request.user.is_superuser:
        commissions = Commission.objects.filter(
            Q(user_profile__exact=profile) | Q(wip__isnull=False))
    else:
        commissions = profile.commissions.all()

    context = {
        'profile': profile,
        'form': form,
        'commissions': commissions,
    }

    return render(request, 'profiles/profile.html', context)

profiles/templates/profiles/profile.html
{% extends "base.html" %}
{% load static %}

{% block extra_title %}
    Profile | {{ profile.user.username }}
{% endblock %}

{% block header %}
    <h3>Hello {{ profile.user.username }}!</h3>
{% endblock %}

{% block content %}
<ul class="collapsible">
    <li>
        <div class="collapsible-header"><i class="material-icons">account_circle</i>Your info</div>
        <form class="collapsible-body" method="POST" action="{% url 'profile' %}">
            {% csrf_token %}
                <div class="row">
                  <div class="input-field col s12 m6">
                    {{ form.first_name }}
                    <label for="id_first_name">First Name</label>
                  </div>
                  <div class="input-field col s12 m6">
                    {{ form.last_name }}
                    <label for="id_last_name">Last Name</label>
                  </div>
                </div>
                <button type="submit" class="btn waves-effect waves-light black"
                        style="margin: 2px;">
                    Update
                </button>
        </form>
    </li>
    <li class="active">
        <div class="collapsible-header"><i class="material-icons">brush</i>Your commissions</div>
        {% if commissions %}
            <table class="highlight responsive-table">
                <thead>
                    <tr>
                        <th>Status</th>
                        <th>Order Number</th>
                        <th>Name</th>
                        <th>Description</th>
                        {% if request.user.is_superuser %}
                            <th>User</th>
                        {% endif %}
                        <th>Details</th>
                    </tr>
                </thead>
                <tbody>
                    {% for commission in commissions %}
                        <tr>
                            <td>
                                {% if commission.artwork.final_illustration %}
                                    Completed
                                {% elif commission.wip.client_comment and not resquest.user.is_superuser %}
                                    Final work in progress
                                {% elif commission.wip.client_comment and resquest.user.is_superuser %}
                                    <i class="material-icons amber-text">star</i> Comment submitted
                                {% elif commission.wip.wip_illustration %}
                                    <i class="material-icons red-text">priority_high</i> Waiting comment
                                {% elif commission.wip and not resquest.user.is_superuser %}
                                    In Progress
                                {% elif commission.wip and resquest.user.is_superuser %}
                                    <i class="material-icons amber-text">star</i> New
                                {% else %}
                                    <i class="material-icons red-text">priority_high</i> Waiting payment
                                {% endif %}
                            </td>
                            <td>{{ commission.order_number|truncatechars:12 }}</td>
                            <td>{{ commission.name|truncatechars:24 }}</td>
                            <td>{{ commission.description|truncatechars:24 }}</td>
                            {% if request.user.is_superuser %}
                                <td>{{ commission.user_profile.user.username|truncatechars:24 }}</td>
                            {% endif %}
                            <td>
                                <a href="{% url 'edit_commission' commission.id %}">
                                    <i class="material-icons">details</i>
                                </a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
            
        {% else %}
            <span class="collapsible-body">You have no commissions</span>
        {% endif %}
    </li>
</ul>

<a href="{% url 'new_commission' %}" class="btn waves-effect waves-light black" style="margin: 2px;">
    <i class="material-icons">add</i> <span>New Commission</span>
</a>

{% endblock %}

{% block postload_js %}
{{ block.super }}
    <script type="text/javascript">
        $(document).ready(function(){
            $('.collapsible').collapsible();
        });
    </script>
{% endblock %}