arts_by_bela/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('profile/', include('profiles.urls')),
    path('commission/', include('commissions.urls')),
    path('payment/', include('payments.urls')),
    path('showcase/', include('showcase.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='home')
]

showcase/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.showcase, name='showcase'),
    path('add/', views.personal_work, name='personal_work')
]

showcase/forms.py
from django import forms


class PersonalWork(forms.Form):
    """
    Form to get name, description and illustration used
    in the personal_work template.
    """
    name = forms.CharField(
        required=True, label=False, max_length=50)
    description = forms.CharField(
        widget=forms.Textarea, required=True, label=False)
    illustration = forms.ImageField(
        required=True, label=False)

    illustration.widget.attrs.update({'hidden': True})
    description.widget.attrs.update({'class': 'materialize-textarea validate'})
    name.widget.attrs.update({'class': 'validate'})

showcase/views.py
from django.shortcuts import render, redirect, reverse
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from commissions import models
from .forms import PersonalWork
from profiles.models import UserProfile


def showcase(request):
    """ A view to return the showcase of all completed artworks """

    artworks = models.Artwork.objects.all()

    context = {
        'artworks': artworks,
    }

    return render(request, 'showcase/showcase.html', context)


@login_required
def personal_work(request):
    """ A view to return the add personal work page """
    if not request.user.is_superuser:
        messages.error(
            request, 'Sorry, only artists can add final artworks')
        return redirect(reverse('showcase'))

    if models.Resolution.objects.count() == 0:
        resolution = models.Resolution.objects.create()
        resolution.save()
    else:
        resolution = models.Resolution.objects.all()[0]

    if models.Size.objects.count() == 0:
        size = models.Size.objects.create()
        size.save()
    else:
        size = models.Size.objects.all()[0]

    if request.method == 'POST':
        form = PersonalWork(request.POST, request.FILES)
        if form.is_valid():
            commission = models.Commission.objects.create(
                user_profile=UserProfile.objects.get(user=request.user),
                name=form.cleaned_data['name'],
                description=form.cleaned_data['description'],
                resolution_price=resolution, size_price=size
            )
            commission.save()
            wip = models.WIP.objects.create(commission=commission)
            wip.save()
            artwork = models.Artwork.objects.create(
                commission=commission,
                client_review=form.cleaned_data['description'],
                final_illustration=form.cleaned_data['illustration'])
            artwork.save()

            return redirect(reverse('showcase'))
        else:
            messages.error(
                request, 'Please ensure the form is valid.')
            form = PersonalWork(request.POST, request.FILES)

    form = PersonalWork()

    context = {
        'form': form,
    }

    return render(request, 'showcase/personal_work.html', context)

showcase/templates/showcase/personal_work.html
{% extends "base.html" %}
{% load static %}

{% block extra_title %}
    New Personal Work
{% endblock %}

{% block header %}
    <h3>Add Personal Work to Showcase</h3>
{% endblock %}

{% block content %}
    <form method="POST" action="{% url 'personal_work' %}" enctype="multipart/form-data">
        {% csrf_token %}
        <h5 class="title-font">Artwork Information</h5>
        <div class="row">
            <div class="input-field col s12">
                {{ form.name }}
                <label for="id_name">Name</label>
            </div>
            <div class="input-field col s12">
                {{ form.description }}
                <label for="id_description">Description</label>
            </div>
        </div>

        <h5 class="title-font">Upload Illustration</h5>
        <label for="id_illustration" class="btn waves-effect waves-light black">Choose File</label>
        <p></p>
        <img class="hide responsive-img" src="#" alt="{{ form.illustration.name }}">
        {{ form.illustration }}

        <div class="row">
            <div class="col s12 xl6">
                <a href="{% url 'showcase' %}" class="btn waves-effect waves-light red" style="margin: 2px;">Cancel</a>
                <button type="submit" class="btn waves-effect waves-light black"
                        style="margin: 2px;">
                    Add
                </button>
            </div>
        </div>
    </form>
{% endblock%}

{% block postload_js %}
    {{ block.super }}
    <script src="{% static 'showcase/js/personal_work_form.js' %}"></script>
{% endblock %}

showcase/templates/showcase/showcase.html
{% extends "base.html" %}
{% load static %}

{% block extra_title %}
    Showcase
{% endblock %}

{% block extra_head %}
    <link rel="stylesheet"
        href="{% static 'showcase/css/showcase.css' %}">
{% endblock %}

{% block header %}
    <h3 class="title-font">Showcase</h3>
{% endblock %}

{% block content %}
    {% if request.user.is_superuser %}
        <a href="{% url 'personal_work' %}" class="btn waves-effect waves-light black" style="margin: 2px;">
            <i class="material-icons">add</i> <span>New Personal Work</span>
        </a>
    {% endif %}
    {% if not artworks %}
        <h5 class="title-font">
            <i class="material-icons">brush</i> Sorry, the artist is still working on illustrations.
        </h5>
    {% else %}
        <div id="showcase-container">
        {% for artwork in artworks %}
            <div class="showcase-item white">
                <img class="responsive-img" src="{{ MEDIA_URL }}{{ artwork.final_illustration.name }}" alt="{{ artwork.final_illustration.name }}">
                <blockquote class="white">
                    {{artwork.commission.name}}
                </blockquote>
                {% if artwork.client_review %}
                    <blockquote class="white">
                        "{{ artwork.client_review }}" <br>
                        <i>- {{ artwork.commission.user_profile.user }}</i>
                    </blockquote>
                {% endif %}
            </div>
        {% endfor %}
        </div>

        <div class="carousel carousel-slider center hide-on-large-only">
            {% for artwork in artworks %}
            <a class="carousel-item" href="#{{ forloop.counter }}!">
                <img class="" src="{{ MEDIA_URL }}{{ artwork.final_illustration.name }}" alt="{{ artwork.final_illustration.name }}">
                <blockquote class="black-text">
                    {{artwork.commission.name}}
                </blockquote>
                {% if artwork.client_review %}
                    <blockquote class="black-text">
                        "{{ artwork.client_review }}" <br>
                        <i>- {{ artwork.commission.user_profile.user }}</i>
                    </blockquote>
                {% endif %}
            </a>
            {% endfor %}
          </div>
    {% endif %}
{% endblock %}

{% block postload_js %}
    {{ block.super }}
    <script src="{% static 'showcase/js/showcase.js' %}"></script>
{% endblock %}