arts_by_bela/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('profile/', include('profiles.urls')),
    path('commission/', include('commissions.urls')),
    path('payment/', include('payments.urls')),
    path('showcase/', include('showcase.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

commissions/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('new/', views.new_commission, name='new_commission'),
    path(
        'edit/<int:commission_id>/', views.edit_commission,
        name='edit_commission'),
    path(
        'delete/<int:commission_id>/', views.delete_commission,
        name='delete_commission'),
    path(
        'wip/<int:commission_id>/', views.wip,
        name='wip'),
    path(
        'artwork/<int:commission_id>/', views.artwork,
        name='artwork'),
]

home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='home')
]

commissions/models.py
import uuid

from django.db import models
from django.core.validators import (
    MaxValueValidator, MinValueValidator)

from profiles.models import UserProfile


class Resolution(models.Model):
    """
    A Resolution model for maintaining the
    resolution options of a illustration.
    """

    class ResolutionsChoices(models.TextChoices):
        LOW = '72 dpi'
        MEDIUM = '144 dpi'
        HIGH = '300 dpi'

    resolution = models.CharField(
        choices=ResolutionsChoices.choices,
        default=ResolutionsChoices.LOW,
        unique=True,
        max_length=7,
    )

    price_factor = models.DecimalField(
        default=1, max_digits=4, decimal_places=2)

    def __str__(self):
        return self.resolution


class Size(models.Model):
    """
    A Size model for maintaining the
    size options of a illustration.
    """

    class SizesChoices(models.TextChoices):
        A4 = 'A4 210 x 297 mm'
        A5 = 'A5 148 x 210 mm'
        A6 = 'A6 105 x 148 mm'
        A7 = 'A7 74 x 105 mm'

    size = models.CharField(
        choices=SizesChoices.choices,
        default=SizesChoices.A7,
        unique=True,
        max_length=15,
    )

    price_factor = models.DecimalField(
        default=1, max_digits=4, decimal_places=2)

    def __str__(self):
        return self.size


class Commission(models.Model):
    """
    A Commission model for maintaining the
    new illustration request information.
    """

    order_number = models.CharField(
        max_length=32, null=False, editable=False,
        unique=True)
    user_profile = models.ForeignKey(
        UserProfile, on_delete=models.PROTECT,
        null=False, blank=False,
        related_name="commissions")
    name = models.CharField(max_length=50, null=False, blank=False)
    description = models.TextField()
    resolution_price = models.ForeignKey(
        'Resolution', on_delete=models.PROTECT,
        null=False, blank=False,
    )
    size_price = models.ForeignKey(
        'Size', on_delete=models.PROTECT,
        null=False, blank=False,
    )
    number_characters = models.SmallIntegerField(
        default=0, null=False, blank=False,
        validators=[MaxValueValidator(
            6, message='Please enter a number below 6'),
            MinValueValidator(
            0, message='Please enter a number above 0')])
    order_total = models.DecimalField(
        max_digits=10, decimal_places=2,
        null=False, default=0)
    reference_image_one = models.ImageField(null=True, blank=True)
    reference_image_two = models.ImageField(null=True, blank=True)
    reference_image_three = models.ImageField(null=True, blank=True)
    reference_image_four = models.ImageField(null=True, blank=True)
    reference_image_five = models.ImageField(null=True, blank=True)

    def _generate_order_number(self):
        """
        Generate a random, unique commission number using UUID
        """
        return uuid.uuid4().hex.upper()

    def _calculate_order_total(self):
        """
        Calculate commission cost
        """
        self.order_total = (
            5*self.resolution_price.price_factor*self.size_price.price_factor +
            2*self.number_characters)

    def _correct_path(self, path, name):
        """
        Define image path. If path already set, just update the file name
        """
        if name.split('/')[0] == path:
            file_name = name.split('/')[-1]
            return f'{path}/references/{file_name}'
        else:
            return f'{path}/references/{name}'

    def _define_file_name(self):
        """
        If the image is uploaded, save image to correct directory
        """
        path = f'{self.order_number}'

        if self.reference_image_one:
            self.reference_image_one.name = self._correct_path(
                path, self.reference_image_one.name)
        if self.reference_image_two:
            self.reference_image_two.name = self._correct_path(
                path, self.reference_image_two.name)
        if self.reference_image_three:
            self.reference_image_three.name = self._correct_path(
                path, self.reference_image_three.name)
        if self.reference_image_four:
            self.reference_image_four.name = self._correct_path(
                path, self.reference_image_four.name)
        if self.reference_image_five:
            self.reference_image_five.name = self._correct_path(
                path, self.reference_image_five.name)

    def save(self, *args, **kwargs):
        """
        Override the original save method to set the order number
        if it hasn't been set already
        """
        if not self.order_number:
            self.order_number = self._generate_order_number()
        self._define_file_name()
        self._calculate_order_total()
        super().save(*args, **kwargs)

    def __str__(self):
        return f'{self.order_number}: {self.name}'


class WIP(models.Model):
    """
    A Work in Progress (WIP) model
    to link to the Commission once paid
    and hold the WIP illustration and client comment
    """
    commission = models.OneToOneField(
        Commission, on_delete=models.CASCADE,
        related_name="wip")
    client_comment = models.TextField(null=False, blank=True)
    wip_illustration = models.ImageField(null=True, blank=True)

    def _correct_path(self, path, name):
        """
        Define image path. If path already set, just update the file name
        """
        if name.split('/')[0] == path:
            file_name = name.split('/')[-1]
            return f'{path}/WIP/{file_name}'
        else:
            return f'{path}/WIP/{name}'

    def save(self, *args, **kwargs):
        """
        Override the original save method to set uploaded file path
        """
        if self.wip_illustration:
            self.wip_illustration.name = self._correct_path(
                f'{self.commission.order_number}', self.wip_illustration.name)

        super().save(*args, **kwargs)

    def __str__(self):
        return f'{self.commission.order_number}: {self.commission.name}'


class Artwork(models.Model):
    """
    A Artwork model
    to link to the Commission once client comment is received
    and hold the final illustation and client review
    """
    commission = models.OneToOneField(
        Commission, on_delete=models.CASCADE,
        related_name="artwork")
    client_review = models.TextField(null=False, blank=True)
    final_illustration = models.ImageField(null=True, blank=True)

    def _correct_path(self, path, name):
        """
        Define image path. If path already set, just update the file name
        """
        if name.split('/')[0] == path:
            file_name = name.split('/')[-1]
            return f'{path}/{file_name}'
        else:
            return f'{path}/{name}'

    def save(self, *args, **kwargs):
        """
        Override the original save method to set uploaded file path
        """
        if self.final_illustration:
            self.final_illustration.name = self._correct_path(
                f'{self.commission.order_number}',
                self.final_illustration.name)

        super().save(*args, **kwargs)

    def __str__(self):
        return f'{self.commission.order_number}: {self.commission.name}'

commissions/forms.py
from django import forms
from . import models


class CommissionForm(forms.ModelForm):
    """
    Commission Model Form to select and format desired fields for
    new_commission and edit_commission templates
    """
    class Meta:
        model = models.Commission
        exclude = ('user_profile', 'order_number', 'order_total')

    resolution_price = forms.ModelChoiceField(
        queryset=None, empty_label=None, to_field_name="resolution")
    size_price = forms.ModelChoiceField(
        queryset=None, empty_label=None, to_field_name="size")

    def __init__(self, *args, **kwargs):
        """
        Add placeholders and classes, remove auto-generated
        labels and set autofocus on first field
        """
        super().__init__(*args, **kwargs)
        self.fields['resolution_price'].queryset = (
            models.Resolution.objects.all())
        self.fields['size_price'].queryset = (
            models.Size.objects.all())
        self.fields['number_characters'].widget.attrs['min'] = 0
        self.fields['number_characters'].widget.attrs['max'] = 6

        for field in self.fields:
            if field == 'description':
                self.fields[field].widget.attrs['class'] = (
                    'materialize-textarea validate')
            else:
                self.fields[field].widget.attrs['class'] = ('validate')
            self.fields[field].label = False


class IllustrationForm(forms.Form):
    """
    Form to relate with wip_illustration and
    final_illustration fields of WIP and Artwork models
    """
    illustration = forms.ImageField(
        required=True, label=False)

    illustration.widget.attrs.update({'hidden': True})


class CommentForm(forms.Form):
    """
    Form to relate with client_comment and
    client_review fields of WIP and Artwork models
    """
    comment = forms.CharField(
        widget=forms.Textarea, required=True, label=False)

    comment.widget.attrs.update({'class': 'materialize-textarea validate'})

commissions/templates/commissions/artwork_details.html
{% extends "base.html" %}
{% load static %}
{% load split_filter %}

{% block extra_title %}
    Artwork | {{ commission.order_number}}
{% endblock %}

{% block extra_head %}
    <link rel="stylesheet"
        href="{% static 'commissions/css/mood_board_collapsible.css' %}">
{% endblock %}

{% block header %}
    <h3>Final Illustration</h3>
{% endblock %}

{% block content %}
    <!-- Commission content -->
    {% include 'commissions/includes/commission_details.html' %}

    <!-- WIP content -->
    {% if wip.wip_illustration and wip.client_comment %}
        {% include 'commissions/includes/progress_details.html' %}
    {% endif %}

    <!-- Artwork forms -->
    <div class="row">
        <div class="col s12">
            {% if not artwork.final_illustration %}
                {% if request.user.is_superuser %}
                    {% include 'commissions/includes/upload_illustration_form.html' %}
                {% else %}
                    <h5 class="title-font">
                        <i class="material-icons">brush</i> The artist is working on your illustration. 
                    </h5>
                {% endif %}
            {% else %}
                <div class="card-panel grey">
                    <h5 class="title-font">Uploaded Illustration</h5>
                    <p>File Name: {{ artwork.final_illustration.name|split:"/"|last }} </p>
                    <img class="responsive-img" src="{{ MEDIA_URL }}{{ artwork.final_illustration.name }}" alt="{{ artwork.final_illustration.name }}">
                    {% if not request.user.is_superuser and not artwork.client_review %}
                          <form class="row" method="POST" action="{% url 'artwork' commission.id %}">
                            {% csrf_token %}
                            <p>I would love to hear what you think of my work. Please leave a review below.</p>
                            <div class="input-field col s12 white z-depth-1">
                                {{ form_comment.comment }}
                                <label for="id_comment">Review</label>
                            </div>
                            <button type="submit" class="btn waves-effect waves-light black"
                                style="margin: 2px;">
                                Submit Review
                            </button>
                        </form>
                    {% elif artwork.client_review %}
                        <h5>Client Review</h5>
                        <blockquote>
                            "{{ artwork.client_review }}" <br>
                            <i>- {{ commission.user_profile.user }}</i>
                        </blockquote>
                    {% endif %}
                    <a href="{{ MEDIA_URL }}{{ artwork.final_illustration.name }}" class="btn waves-effect waves-light black"
                        style="margin: 2px;" target="_blank" download>Download</a>
                </div>
            {% endif %}
        </div>
    </div>

    <div class="row">
        <div class="col s12">
            <a href="{% url 'profile' %}" class="btn waves-effect waves-light red" style="margin: 2px;">Return to Profile</a>
        </div>
    </div>
{% endblock%}

{% block postload_js %}
{{ block.super }}  
    <script src="{% static 'commissions/js/single_image_preview.js' %}"></script>
{% endblock %}

commissions/templates/commissions/edit_commission.html
{% extends "base.html" %}
{% load static %}

{% block extra_title %}
    Edit Commission | {{ commission.order_number }}
{% endblock %}

{% block header %}
    <h3>Tell me your ideas below</h3>
{% endblock %}

{% block content %}
    <form method="POST" action="{% url 'edit_commission' commission.id %}" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="row">
            <div class="col s12 xl6">
                <h5>Illustration requirements:</h5>
                <div class="row">
                    <div class="input-field col s12 m4">
                    {{ form.name }}
                    <label for="id_name">Name</label>
                    </div>
                    <div class="input-field col s12 m8">
                        {{ form.description }}
                        <label for="id_description">Description</label>
                    </div>
                </div>
                <div class="row" id="calculator-select">
                    <div class="input-field col s6 m4">
                        {{ form.size_price }}
                        <label for="id_size_price">Size</label>
                    </div>
                    <div class="input-field col s6 m4">
                        {{ form.resolution_price }}
                        <label for="id_resolution_price">Resolution</label>
                    </div>
                    <div class="input-field col s6 m4">
                        {{ form.number_characters }}
                        <label for="id_number_characters">Number of Characters</label>
                        <span class="helper-text">Up to 6 characters</span>
                    </div>
                </div>
            </div>
            
            <!-- Mood Board -->
            <div class="col s12 xl6">
                <div class="card-panel grey">
                    <h5>Mood board: </h5>
                    <div class="row">
                        {% for field in form %}
                            {% if field.widget_type == 'clearablefile'%}
                            <div class="col s6 xl4">
                                <div class="btn-floating btn-large waves-effect waves-light black mood-board-button"><i class="material-icons">add</i>{{ field }}</div>
                                <div class="mood-board-image">
                                    <img src="#" alt="{{ field.name }}">
                                    <p></p>
                                    <p><strong class="red-text waves-effect waves-black btn-flat">Remove</strong></p>
                                </div>
                            </div>
                            {% endif %}
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <h5 class="col s12">Total: <strong id="your-quote"></strong></h5>
        </div>

        <div class="row">
            <div class="col s12 xl6">
                <a href="{% url 'profile' %}" class="btn waves-effect waves-light red" style="margin: 2px;">Cancel</a>
                <a href="#delete-confirm" class="modal-trigger btn waves-effect waves-light red" style="margin: 2px;">Delete</a>
                <button type="submit" class="btn waves-effect waves-light black"
                        style="margin: 2px;">
                    Proceed to payment
                </button>
            </div>
        </div>
    </form>

  <!-- Modal Structure -->
  <div id="delete-confirm" class="modal">
    <div class="modal-content">
        <h4 class="red-text title-font">WARNING!</h4>
        <p>The commission order: "{{ commission.order_number }}" will be deleted. All info and files will be lost.</p>
        <p>Are you sure you want to proceed?</p>
    </div>
    <div class="modal-footer">
        <a href="#"
        class="modal-close waves-effect waves-green btn red">Cancel</a>
        <a href="{% url 'delete_commission' commission.id %}"
        class="modal-close waves-effect waves-green btn red">Proceed</a>
    </div>
  </div>
{% endblock%}

{% block postload_js %}
    {{ block.super }}

    {{ json_data|json_script:"json-data" }}
    {{ commission.resolution_price.resolution|json_script:"commission-resolution"}}
    {{ commission.size_price.size|json_script:"commission-size"}}
    <script src="{% static 'js/quote_calculator.js' %}"></script>
    <script src="{% static 'commissions/js/mood_board.js' %}"></script>
    <script src="{% static 'commissions/js/select_resolution_size.js' %}"></script>
{% endblock %}

commissions/templates/commissions/new_commission.html
{% extends "base.html" %}
{% load static %}

{% block extra_title %}
    New Commission
{% endblock %}

{% block header %}
    <h3>Tell me your ideas below</h3>
{% endblock %}

{% block content %}
    <form method="POST" action="{% url 'new_commission' %}" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="row">
            <div class="col s12 xl6">
                <h5>Illustration requirements:</h5>
                <div class="row">
                    <div class="input-field col s12 m4">
                    {{ form.name }}
                    <label for="id_name">Name</label>
                    </div>
                    <div class="input-field col s12 m8">
                        {{ form.description }}
                        <label for="id_description">Description</label>
                    </div>
                </div>
                <div class="row" id="calculator-select">
                    <div class="input-field col s6 m4">
                        {{ form.size_price }}
                        <label for="id_size_price">Size</label>
                    </div>
                    <div class="input-field col s6 m4">
                        {{ form.resolution_price }}
                        <label for="id_resolution_price">Resolution</label>
                    </div>
                    <div class="input-field col s6 m4">
                        {{ form.number_characters }}
                        <label for="id_number_characters">Number of Characters</label>
                        <span class="helper-text">Up to 6 characters</span>
                    </div>
                </div>
            </div>
            
            <!-- Mood Board -->
            <div class="col s12 xl6">
                <div class="card-panel grey">
                    <h5>Mood board: </h5>
                    <div class="row">
                        {% for field in form %}
                            {% if field.widget_type == 'clearablefile'%}
                            <div class="col s6 xl4">
                                <div class="btn-floating btn-large waves-effect waves-light black mood-board-button"><i class="material-icons">add</i>{{ field }}</div>
                                <div class="mood-board-image">
                                    <img src="#" alt="{{ field.name }}">
                                    <p></p>
                                    <p><strong class="red-text waves-effect waves-black btn-flat">Remove</strong></p>
                                </div>
                            </div>
                            {% endif %}
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <h5 class="col s12">Total: <strong id="your-quote"></strong></h5>
        </div>

        <div class="row">
            <div class="col s12 xl6">
                <a href="{% url 'profile' %}" class="btn waves-effect waves-light red" style="margin: 2px;">Cancel</a>
                <button type="submit" class="btn waves-effect waves-light black"
                        style="margin: 2px;">
                    Proceed to payment
                </button>
            </div>
        </div>
    </form>
{% endblock%}

{% block postload_js %}
    {{ block.super }}

    {{ json_data|json_script:"json-data" }}
    <script src="{% static 'js/quote_calculator.js' %}"></script>
    <script src="{% static 'commissions/js/mood_board.js' %}"></script>
{% endblock %}

commissions/templates/commissions/wip_details.html
{% extends "base.html" %}
{% load static %}
{% load split_filter %}

{% block extra_title %}
    WIP | {{ commission.order_number}}
{% endblock %}

{% block extra_head %}
    <link rel="stylesheet"
        href="{% static 'commissions/css/mood_board_collapsible.css' %}">
{% endblock %}

{% block header %}
    <h3>Commission in progress</h3>
{% endblock %}

{% block content %}
    <!-- Commission content -->
    <div class="row">
        <div class="col s12">
            <table class="highlight responsive-table">
                <thead>
                    <tr>
                        <th>Order Number</th>
                        <th>Name</th>
                        <th>Description</th>
                        <th>Size</th>
                        <th>Resolution</th>
                        <th>Number of Characters</th>
                        <th>Total</th>
                    </tr>
                </thead>
                <tbody>
                        <tr>
                            <td>{{ commission.order_number }}</td>
                            <td>{{ commission.name }}</td>
                            <td>{{ commission.description }}</td>
                            <td>{{ commission.size_price.size }}</td>
                            <td>{{ commission.resolution_price.resolution }}</td>
                            <td>{{ commission.number_characters }}</td>
                            <td>$ {{ commission.order_total }}</td>
                        </tr>
                </tbody>
            </table>
        </div>

        <div class="col s12">
            <div class="card-panel grey">
                <ul class="collapsible">
                    <li>
                        <h5 class="collapsible-header">
                            Mood board: <i class="material-icons">expand_more</i>
                        </h5>
                        <div class="collapsible-body row">
                            {% if commission.reference_image_one %}
                                <div class="col s6 xl4">
                                    <div class="mood-board-image">
                                        <img src="{{ MEDIA_URL }}{{ commission.reference_image_one.name }}" alt="{{ commission.reference_image_one.name }}">
                                    </div>
                                </div>
                            {% endif %}
                            {% if commission.reference_image_two %}
                                <div class="col s6 xl4">
                                    <div class="mood-board-image">
                                        <img src="{{ MEDIA_URL }}{{ commission.reference_image_two.name }}" alt="{{ commission.reference_image_two.name }}">
                                    </div>
                                </div>
                            {% endif %}
                            {% if commission.reference_image_three %}
                                <div class="col s6 xl4">
                                    <div class="mood-board-image">
                                        <img src="{{ MEDIA_URL }}{{ commission.reference_image_three.name }}" alt="{{ commission.reference_image_three.name }}">
                                    </div>
                                </div>
                            {% endif %}
                            {% if commission.reference_image_four %}
                                <div class="col s6 xl4">
                                    <div class="mood-board-image">
                                        <img src="{{ MEDIA_URL }}{{ commission.reference_image_four.name }}" alt="{{ commission.reference_image_four.name }}">
                                    </div>
                                </div>
                            {% endif %}
                            {% if commission.reference_image_five %}
                                <div class="col s6 xl4">
                                    <div class="mood-board-image">
                                        <img src="{{ MEDIA_URL }}{{ commission.reference_image_five.name }}" alt="{{ commission.reference_image_five.name }}">
                                    </div>
                                </div>
                            {% endif %}
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </div>

    <!-- WIP forms -->
    <div class="row">
        <div class="col s12">
            {% if not commission.wip.wip_illustration %}
                {% if request.user.is_superuser %}
                    {% include 'commissions/includes/upload_illustration_form.html' %}
                {% else %}
                    <h5 class="title-font">
                        <i class="material-icons">brush</i> The artist is working on your illustration. 
                    </h5>
                {% endif %}
            {% else %}
                <div class="card-panel grey">
                    <h5 class="title-font">Uploaded Illustration</h5>
                    <p>File Name: {{ wip.wip_illustration.name|split:"/"|last }} </p>
                    <img class="responsive-img" src="{{ MEDIA_URL }}{{ wip.wip_illustration.name }}" alt="{{ wip.wip_illustration.name }}">
                    {% if not request.user.is_superuser %}
                          <form class="row" method="POST" action="{% url 'wip' commission.id %}">
                            {% csrf_token %}
                            <h6>Include your comments below:</h6>
                            <div class="input-field col s12 white z-depth-1">
                                {{ form.client_comment }}
                                <label for="id_client_comment">Comments</label>
                            </div>
                            <button type="submit" class="btn waves-effect waves-light black"
                                style="margin: 2px;">
                                Submit Comment
                            </button>
                        </form>  
                    {% endif %}
                </div>
            {% endif %}
        </div>
    </div>

    <div class="row">
        <div class="col s12">
            <a href="{% url 'profile' %}" class="btn waves-effect waves-light red" style="margin: 2px;">Return to Profile</a>
        </div>
    </div>
{% endblock%}

{% block postload_js %}
{{ block.super }}  
    <script src="{% static 'commissions/js/single_image_preview.js' %}"></script>
{% endblock %}